#!/usr/bin/env python3

import os, sys

if len(sys.argv) != 3:
	print('lvs: E necessario specificare 2 nomi di netlist da comparare.')
	sys.exit(1)
os.system('netgen -batch lvs {} {} /foss/designs/PDK/sky130B/libs.tech/netgen/sky130B_setup.tcl'.format(sys.argv[1],sys.argv[2]))
sys.exit(0)
